channels:
- conda-forge
- defaults
dependencies:
- python =3.12
- pip
- numpy
- astropy
- ipykernel
- gfortran
- gcc
- gxx
- boost
- ply
- libx11-devel-cos7-x86_64
# - tcllib
# - tk
- make
- meson =1.4.0
- sphinx
- pytest
- scipy
- pandas
- pkg-config
- perl
- gawk
- sed
- coreutils
- cmake
- xorg-libx11
- xorg-libxt
- xorg-libxext
- xorg-xproto
- xorg-xextproto
- xorg-kbproto
- libxcb
- cfitsio
- wcslib
- fftw
- pybind11
# - build
- wheel
- setuptools