channels:
- conda-forge
- defaults
dependencies:
- python
- pip
- numpy
- astropy
- ipykernel
- gfortran =8.5.0
- gcc =8.5.0
- gxx =8.5.0
- boost
- ply
- libx11-devel-cos7-x86_64
# - tcllib
# - tk
- make
- meson =1.4.0
- sphinx
- pytest
- scipy
- pandas
- pkg-config
- perl
- gawk
- sed
- coreutils
- cmake
- xorg-libx11
- xorg-libxt
- xorg-libxext
- xorg-xproto
- xorg-xextproto
- xorg-kbproto
- libxcb
- cfitsio
- wcslib
- fftw